//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WumpusTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WumpusTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowTarget {
            get {
                object obj = ResourceManager.GetObject("ArrowTarget", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CaveBackground {
            get {
                object obj = ResourceManager.GetObject("CaveBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions:
        ///- Objective is to kill the Wumpus by shooting it from an adjacent room
        ///- Use the arrow keys to move around each room
        ///- “I smell a Wumpus” means the Wumpus is in an adjacent room.
        /// </summary>
        internal static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MainMenuBackground {
            get {
                object obj = ResourceManager.GetObject("MainMenuBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap North_Door {
            get {
                object obj = ResourceManager.GetObject("North_Door", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap North_NoDoor {
            get {
                object obj = ResourceManager.GetObject("North_NoDoor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Northeast_Door {
            get {
                object obj = ResourceManager.GetObject("Northeast_Door", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Northeast_NoDoor {
            get {
                object obj = ResourceManager.GetObject("Northeast_NoDoor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Northwest_Door {
            get {
                object obj = ResourceManager.GetObject("Northwest_Door", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Northwest_NoDoor {
            get {
                object obj = ResourceManager.GetObject("Northwest_NoDoor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The largest country in Europe is Russia.
        ///The smallest country in the world is Vatican City.
        ///Moby Dick is written by Herman Melville.
        ///Bats are in room
        ///The Wumpus likes to eat carrots.
        ///The largest organ in the human body is the skin.
        ///The largest internal organ in the human body is the liver.
        ///In the average lifetime, a person will walk the equivalent of 5 times around the equator.
        ///Odontophobia is the fear of teeth.
        ///You are in room
        ///The capital of Honduras is Tegucigarpa.
        ///Triskadekaphobia is the fear  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Secrets {
            get {
                return ResourceManager.GetString("Secrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap South_Door {
            get {
                object obj = ResourceManager.GetObject("South_Door", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap South_NoDoor {
            get {
                object obj = ResourceManager.GetObject("South_NoDoor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Southeast_Door {
            get {
                object obj = ResourceManager.GetObject("Southeast_Door", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Southeast_NoDoor {
            get {
                object obj = ResourceManager.GetObject("Southeast_NoDoor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Southwest_Door {
            get {
                object obj = ResourceManager.GetObject("Southwest_Door", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Southwest_NoDoor {
            get {
                object obj = ResourceManager.GetObject("Southwest_NoDoor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who invented the telephone?
        ///	Alexander Graham Bell
        ///	Albert Einstein
        ///	Isaac Newton
        ///	Thomas Edison
        ///When did WWII end?
        ///	1945
        ///	1963
        ///	1927
        ///	1944
        ///What planet is closest to the sun?
        ///	Mercury
        ///	Venus
        ///	Jupiter
        ///	Saturn
        ///What is the capital of Honduras?
        ///	Tegucigarpa
        ///	Tela
        ///	Choloma
        ///	Comayagua
        ///What country gave Florida to the US?
        ///	Spain
        ///	France
        ///	Portugal
        ///	Mexico
        ///Who was the president of Vietnam from 1945-1954?
        ///	Ho Chi Min
        ///	Nguyen Xuan Phuc
        ///	Kim Jong-il
        ///	Dang Thi Ngoc Thinh
        ///What animal was ins [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TriviaQuestions {
            get {
                return ResourceManager.GetString("TriviaQuestions", resourceCulture);
            }
        }
    }
}
